version: "3.8"
services:
  express:
    build: ./
    command: npm start
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:15.2
    container_name: postgres_db
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./InitDB.sql:/docker-entrypoint-initdb.d/InitDB.sql
